### ISSUE TITLE
User Management - Index page/Edit/Create

### ISSUE THREAD

**Issue by traday** [traday/irs#3]
## Screen
A list of all users in alphabetical order (last, first name), showing:
| Last | First | email | Officer? | Admin? | Disabled? | Edit icon/button |

## Actions
- Edit Icon/button on a row makes the row editable. Edit icon changes to Save/Cancel.  Save sends _put user/id_ json request
- Create icon/button creates a new row at the top of the list with blank fields and Create/Cancel buttons in the Edit icon/button column of the list.  Create sends _post user_ json request.

## Validation
Password is hidden, must exist, is at least 6 chars, not the same as email.
email: make sure it has an @ symbol and a '.' after the @ or something basic like that.
User can't disable self or remove admin privilege from self.

## Tests
We will test this by hand.

**Comment by bandrben** [comment]
Every person in the person table must have a password?  I don't think we want to require that piece, because we don't want everyone in the fire co. to have a username/password.  Most members will have an anon access to system.  If we go with anon access for submitting incident reports (not approving them), then how do we ensure only our fire co. members are using the system since the system will be hosted on the internet in the cloud somewhere?  IP Address white listing, something machine dependent?  Maybe single sign on with a LONG cookie which must be easy to enter in case the cookie is wiped and the program needs to be ready/accessible after a shutdown/power outage.

(Also, this will be a mission critical system, what happens if the system is down (broken, internet down, blackout, etc)?  The nature of this system is that it has to be used during emergencies which may include power outages.  Plus, what if the system is down, what is our fall back plan, putting it on paper again and then adding those paper records later to IRS just like a backlog to NFIRS)?

Can you imagine the 50+ users and common helpdesk tasks for them ("I forgot my password, reset it.").  Unless you automate the password reset, requiring email sending and a temp code (and maybe awful secret questions and answers, another thing to forget).  But we also have a diverse membership and many of our users have little to no experience with IT system.

**Comment by MatthewTFarley** [comment]
@bandrben according to the [wiki](https://github.com/traday/irs/wiki/Requirements) the majority of users will share a single generic account. Only officer and admin level users will have their own email/password.

**Comment by traday** [comment]
Ben, I am making a distinction between users and personnel.  Users are described here, and there are only user accounts for Admins (you and me), officers, and a generic input account, which you call "anon".

Ultimate fallback is putting it back on paper, yes.
